### PR TITLE
#55 http redirects are not honoured

### LINKED ISSUE #55: HTTP redirects (3xx status codes) are not honoured
From the Shapeshifter specification: "when using HTTP version 1.1, redirects (responses with status code 3xx) should be honored in order to support load balancing. "

Currently the Java library does not honour the 3xx status codes and throws an exception instead.

302, 307 status codes should be implemented so that the request is retried against the URL in the Location header.
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307
Also:  HTTP 308 https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308

303 should not be honoured as it changes the method to GET which is not compliant. See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303 

301 could be implemented similar to 302 and 307.

Implementation notes:
- Probably need to change UftpSendMessageService
- Throw exception if no Location header available
- Don't follow redirects infinitely: let's set a max amount of redirects to follow for one initial request

### PR DESCRIPTION
**Pull request by tomwetjens**
fixes #55

### CODE REVIEW

File: core/src/main/java/org/lfenergy/shapeshifter/core/service/sending/UftpSendMessageService.java [hunk 1]
```diff
@@ -33,114 +35,142 @@
...
+                } else {
+                    throw new UftpSendException(MessageFormat.format(MSG_UNEXPECTED_RESPONSE_STATUS, response.statusCode(), url, response.body()), httpStatusCode);
+                }
+            }
+        } catch (URISyntaxException | IllegalArgumentException e) {
+            throw new UftpSendException(MessageFormat.format(MSG_INVALID_ENDPOINT, e.getMessage()), e);
+        } catch (IOException e) {
+            throw new UftpSendException(MessageFormat.format(MSG_UNEXPECTED_IO_ERROR, url, e.getMessage()), e);
+        } catch (InterruptedException e) {
+            Thread.currentThread().interrupt();
```
Comment (eelcodenheijer) [inline core/src/main/java/org/lfenergy/shapeshifter/core/service/sending/UftpSendMessageService.java:172]: one last question: why do we need `Thread.currentThread().interrupt()` - it suggests that this code is running on a separate thread or something?

Comment (tomwetjens) [reply core/src/main/java/org/lfenergy/shapeshifter/core/service/sending/UftpSendMessageService.java:172]: Indeed, the `httpClient.send(...)` call can throw an `InterruptedException`.

The addition of `Thread.currentThread().interrupt();` was to fix a SonarQube warning that we must always mark the current thread as interrupted when catching an `InterruptedException`

Comment (eelcodenheijer) [reply core/src/main/java/org/lfenergy/shapeshifter/core/service/sending/UftpSendMessageService.java:172]: Ah, ok...
